"""empty message

Revision ID: 8b2452c5942d
Revises: 2526e953b7d7
Create Date: 2025-12-30 13:16:11.357724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2452c5942d'
down_revision = '2526e953b7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('item')
        batch_op.drop_column('title2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title2', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('item', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
